
conectaBBDD(){


SQL_HOST=192.168.29.166
SQL_PORT=3305
SQL_USER="U1014224787"
SQL_PASSWORD="kGCR2Sp-J9u*5w"
SQL_DATABASE="ZEUS"
SQL_ARGS="-h $SQL_HOST -P $SQL_PORT -u $SQL_USER -p$SQL_PASSWORD -D $SQL_DATABASE -s -e"

RESULTADOCONSULTA=$(mysql $SQL_ARGS "select PROD_ID from ZEUS.PRODUCTO where SUBPRODUCTO =$1 and eancode like '$2%' order by PROD_ID desc limit 1;")
echo $RESULTADOCONSULTA

}

insert_productos_validacion_cuentas(){

insert_getrax=$( echo "
INSERT INTO ZEUS.VALIDACIONCUENTAS
(VALCU_BUSINESSMODEL, VALCU_TIPOMAYORISTA, VALCU_TIPOPUNTO, PROD_ID, TICU_ID, CUENTAPRINCIPAL, TITR_ID, VALCU_FECHAREGISTRO)
VALUES('PTOPRE', 8, 13, PROD_ID, 100, 1, NULL, NOW());

INSERT INTO ZEUS.VALIDACIONCUENTAS
(VALCU_BUSINESSMODEL, VALCU_TIPOMAYORISTA, VALCU_TIPOPUNTO, PROD_ID, TICU_ID, CUENTAPRINCIPAL, TITR_ID, VALCU_FECHAREGISTRO)
VALUES('ALIANZAPRE', 8, 13, PROD_ID, 10, 1,  NULL, NOW());

INSERT INTO ZEUS.VALIDACIONCUENTAS
(VALCU_BUSINESSMODEL, VALCU_TIPOMAYORISTA, VALCU_TIPOPUNTO, PROD_ID, TICU_ID, CUENTAPRINCIPAL, TITR_ID, VALCU_FECHAREGISTRO)
VALUES('ALIANZAPOS', 8, 13, PROD_ID, 10, 1,  NULL, NOW());

INSERT INTO ZEUS.VALIDACIONCUENTAS
(VALCU_BUSINESSMODEL, VALCU_TIPOMAYORISTA, VALCU_TIPOPUNTO, PROD_ID, TICU_ID, CUENTAPRINCIPAL, TITR_ID, VALCU_FECHAREGISTRO)
VALUES('FRAMULT', 8, 13, PROD_ID, 130, 1, NULL, NOW());")
insert_getrax=${insert_getrax//PROD_ID/$1}
echo -e  "  \n $insert_getrax"
}

echo -e "\n\n\n\n\n--  #################################### INSERT VALIDACION CUENTA #################################### "
echo -e "\n\n\n\n\n--  #################################### INSERT VALIDACION CUENTA #################################### " > inactivos/insert_inactivos/insert_validacion_cuenta.txt
con=1
while IFS=\# read -r operador product_code eancode valor vigencia subtype cedula descripcion  ;
 do
#verifica si existe un operdor direferente a tigo o claro en el tx.list y lo ignora
if [[ "$operador" != "TIGO" && "$operador" != "CLARO"  ]]; then
echo "paquete solo tranza por mahindra [$con]"
con=$((con +1))
continue
fi

#recuoera ek PROD_ID de cada paquete a traves d ela guncion concectaBBDD
id_bd=$(conectaBBDD $product_code $eancode)
#echo "$id_bd"

#varIable que ecoje el resultado de la funcion insert_productos_producto_cliente

insert__validacion_cuenta=$(insert_productos_validacion_cuentas $id_bd)


#imprime pantalla
echo -e  "\n\n--  xxxxxxxxxxxxxxxxxxxxxxxxxx insert $product_code ($id_bd) $operador [$con] xxxxxxxxxxxxxxxxxxxxxxxxxx  \n "
echo -e "$insert__validacion_cuenta"

#imprime archivo
echo -e  "\n\n--  xxxxxxxxxxxxxxxxxxxxxxxxxx insert $product_code ($id_bd) $operador [$con] xxxxxxxxxxxxxxxxxxxxxxxxxx  \n " >> inactivos/insert_inactivos/insert_validacion_cuenta.txt
echo -e "$insert__validacion_cuenta">> inactivos/insert_inactivos/insert_validacion_cuenta.txt

### xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

con=$((con+1))

##SE CIERRA EL WHILE
 done < tx.list




#producto cliente


conectaBBDD(){


SQL_HOST=192.168.29.166
SQL_PORT=3305
SQL_USER="U1014224787"
SQL_PASSWORD="kGCR2Sp-J9u*5w"
SQL_DATABASE="ZEUS"
SQL_ARGS="-h $SQL_HOST -P $SQL_PORT -u $SQL_USER -p$SQL_PASSWORD -D $SQL_DATABASE -s -e"

RESULTADOCONSULTA=$(mysql $SQL_ARGS "select PROD_ID from ZEUS.PRODUCTO where SUBPRODUCTO =$1 and eancode like '$2%'
order by PROD_ID desc limit 1;")
echo $RESULTADOCONSULTA

}

insert_productos_producto_cliente(){

insert_getrax=$( echo "

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175205, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175161, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175125, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175111, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175084, PROD_ID, '1', 24, 0, 0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175055, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175050, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174998, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174971, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174941, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(113896, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174878, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174862, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174830, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(113900, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174654, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174626, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174559, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174558, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174483, PROD_ID, '1', 24, 0, 0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174474, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174453, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174437, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174428, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174409, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174373, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174359, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174341, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174321, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174297, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174238, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(174014, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(173612, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(173465, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(173238, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(172997, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(172865, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(171723, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(170145, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(169949, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(155315, PROD_ID, '1', 24, 0,  0, NULL, NOW());
INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(132328, PROD_ID, '1', 24, 0,  0, NULL, NOW());
INSERT INTO ZEUS.PRODUCTOCLIENTE

(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(118842, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(81303, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175885, PROD_ID, '1', 20, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175943, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176289, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176482, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176516, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176497, PROD_ID, '1', 24, 0, 0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(175323, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176512, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176528, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176536, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176554, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176759, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176805, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176806, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176868, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176877, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176878, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176879, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176880, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176881, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176876, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176923, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176924, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176925, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176926, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176927, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176958, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176966, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(1686, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176983, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176990, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(177022, PROD_ID, '1', 24, 0,  0, NULL, NOW());

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(177030, PROD_ID, '1', 24, 0,  0, NULL, '2020-01-15 14:41:54');

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(176974, PROD_ID, '1', 24, 0, 0, NULL, '2020-08-07 11:47:50');

INSERT INTO ZEUS.PRODUCTOCLIENTE
(TERC_ID, PROD_ID, PROCLI_ESTADO, CNXOP_ID, PROCLI_AVOIDDUPLICATES, PROCLI_CHECKFRAUD, PROCLI_REFERENCIA, PROCLI_FECHAREGISTRO)
VALUES(177160, PROD_ID, '1', 24, 0, 0, NULL, '2020-11-06 14:15:18');

")
insert_getrax=${insert_getrax//PROD_ID/$1}

echo -e  "  \n $insert_getrax"

}



echo -e "\n\n\n\n\n--  #################################### INSERT PRODUCTO_CLIENTE #################################### "
echo -e "\n\n\n\n\n--  #################################### INSERT PRODUCTO_CLIENTE #################################### " > inactivos/insert_inactivos/insert_producto_cliente.txt

con=1

while IFS=\# read -r operador product_code eancode valor vigencia subtype cedula descripcion  ;
 do


#verifica si existe un operador direferente a tigo o claro en el tx.list y lo ignora
if [[ "$operador" != "TIGO" && "$operador" != "CLARO"  ]]; then
continue
fi

#recuoera el PROD_ID de cada paquete a traves d ela funcion concectaBBDD
id_bd=$(conectaBBDD $product_code $eancode)


#varIable que ecoje el resultado de la funcion insert_productos_producto_cliente

insert__producto_cliente=$(insert_productos_producto_cliente $id_bd)

#imprime pantalla
echo -e  "\n\n--  xxxxxxxxxxxxxxxxxxxxxxxxxx insert $product_code ($id_bd) $operador [$con] xxxxxxxxxxxxxxxxxxxxxxxxxx  \n "
echo -e "$insert__producto_cliente"

#imprime archivo
echo -e  "\n\n--  xxxxxxxxxxxxxxxxxxxxxxxxxx insert $product_code ($id_bd) $operador [$con] xxxxxxxxxxxxxxxxxxxxxxxxxx  \n " >> inactivos/insert_inactivos/insert_producto_cliente.txt
echo -e "$insert__producto_cliente">> inactivos/insert_inactivos/insert_producto_cliente.txt

### xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

con=$((con+1))

##SE CIERRA EL WHILE
 done < tx.list

